/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppFornecedoresRouteRouteImport } from './routes/_app/fornecedores/route'
import { Route as AppLojasRouteImport } from './routes/_app/lojas'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AuthCadastroRouteImport } from './routes/_auth/cadastro'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppFornecedoresIndexRouteImport } from './routes/_app/fornecedores/index'
import { Route as AppFornecedoresSupplierIdRouteImport } from './routes/_app/fornecedores/$supplierId'
import { Route as AppPublicacoesIndexRouteImport } from './routes/_app/publicacoes/index'
import { Route as AppPublicacoesNovaRouteImport } from './routes/_app/publicacoes/nova'
import { Route as AppSuporteIndexRouteImport } from './routes/_app/suporte/index'
import { Route as AppSuporteTicketIdRouteImport } from './routes/_app/suporte/$ticketId'
import { Route as AppSuporteNovoRouteImport } from './routes/_app/suporte/novo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFinanceiroExportarRouteImport } from './routes/api/financeiro/exportar'
import { Route as ApiWebhooksMarketplaceRouteImport } from './routes/api/webhooks/$marketplace'
import { Route as OauthMockAutorizarRouteImport } from './routes/oauth/mock/autorizar'
import { Route as AppAdminChamadosIndexRouteImport } from './routes/_app/admin/chamados/index'
import { Route as AppAdminChamadosTicketIdRouteImport } from './routes/_app/admin/chamados/$ticketId'
import { Route as ApiOauthMarketplaceCallbackRouteImport } from './routes/api/oauth/$marketplace/callback'
import { Route as ApiOauthMarketplaceStartRouteImport } from './routes/api/oauth/$marketplace/start'
import { Route as ApiSuporteAnexosAttachmentIdRouteImport } from './routes/api/suporte/anexos/$attachmentId'
import { Route as ApiSuporteChamadosIndexRouteImport } from './routes/api/suporte/chamados/index'
import { Route as ApiAdminChamadosTicketIdMensagensRouteImport } from './routes/api/admin/chamados/$ticketId/mensagens'
import { Route as ApiSuporteChamadosTicketIdMensagensRouteImport } from './routes/api/suporte/chamados/$ticketId/mensagens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFornecedoresRouteRoute = AppFornecedoresRouteRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLojasRoute = AppLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppFornecedoresIndexRoute = AppFornecedoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFornecedoresRouteRoute,
} as any)
const AppFornecedoresSupplierIdRoute =
  AppFornecedoresSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => AppFornecedoresRouteRoute,
  } as any)
const AppPublicacoesIndexRoute = AppPublicacoesIndexRouteImport.update({
  id: '/publicacoes/',
  path: '/publicacoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPublicacoesNovaRoute = AppPublicacoesNovaRouteImport.update({
  id: '/publicacoes/nova',
  path: '/publicacoes/nova',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuporteIndexRoute = AppSuporteIndexRouteImport.update({
  id: '/suporte/',
  path: '/suporte/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuporteTicketIdRoute = AppSuporteTicketIdRouteImport.update({
  id: '/suporte/$ticketId',
  path: '/suporte/$ticketId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuporteNovoRoute = AppSuporteNovoRouteImport.update({
  id: '/suporte/novo',
  path: '/suporte/novo',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceiroExportarRoute = ApiFinanceiroExportarRouteImport.update({
  id: '/api/financeiro/exportar',
  path: '/api/financeiro/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMarketplaceRoute = ApiWebhooksMarketplaceRouteImport.update({
  id: '/api/webhooks/$marketplace',
  path: '/api/webhooks/$marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMockAutorizarRoute = OauthMockAutorizarRouteImport.update({
  id: '/oauth/mock/autorizar',
  path: '/oauth/mock/autorizar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminChamadosIndexRoute = AppAdminChamadosIndexRouteImport.update({
  id: '/chamados/',
  path: '/chamados/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminChamadosTicketIdRoute =
  AppAdminChamadosTicketIdRouteImport.update({
    id: '/chamados/$ticketId',
    path: '/chamados/$ticketId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const ApiOauthMarketplaceCallbackRoute =
  ApiOauthMarketplaceCallbackRouteImport.update({
    id: '/api/oauth/$marketplace/callback',
    path: '/api/oauth/$marketplace/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMarketplaceStartRoute =
  ApiOauthMarketplaceStartRouteImport.update({
    id: '/api/oauth/$marketplace/start',
    path: '/api/oauth/$marketplace/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSuporteAnexosAttachmentIdRoute =
  ApiSuporteAnexosAttachmentIdRouteImport.update({
    id: '/api/suporte/anexos/$attachmentId',
    path: '/api/suporte/anexos/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSuporteChamadosIndexRoute = ApiSuporteChamadosIndexRouteImport.update({
  id: '/api/suporte/chamados/',
  path: '/api/suporte/chamados/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChamadosTicketIdMensagensRoute =
  ApiAdminChamadosTicketIdMensagensRouteImport.update({
    id: '/api/admin/chamados/$ticketId/mensagens',
    path: '/api/admin/chamados/$ticketId/mensagens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSuporteChamadosTicketIdMensagensRoute =
  ApiSuporteChamadosTicketIdMensagensRouteImport.update({
    id: '/api/suporte/chamados/$ticketId/mensagens',
    path: '/api/suporte/chamados/$ticketId/mensagens',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/fornecedores': typeof AppFornecedoresRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/lojas': typeof AppLojasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/cadastro': typeof AuthCadastroRoute
  '/login': typeof AuthLoginRoute
  '/fornecedores/$supplierId': typeof AppFornecedoresSupplierIdRoute
  '/publicacoes/nova': typeof AppPublicacoesNovaRoute
  '/suporte/$ticketId': typeof AppSuporteTicketIdRoute
  '/suporte/novo': typeof AppSuporteNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/financeiro/exportar': typeof ApiFinanceiroExportarRoute
  '/api/webhooks/$marketplace': typeof ApiWebhooksMarketplaceRoute
  '/oauth/mock/autorizar': typeof OauthMockAutorizarRoute
  '/fornecedores/': typeof AppFornecedoresIndexRoute
  '/publicacoes/': typeof AppPublicacoesIndexRoute
  '/suporte/': typeof AppSuporteIndexRoute
  '/admin/chamados/$ticketId': typeof AppAdminChamadosTicketIdRoute
  '/api/oauth/$marketplace/callback': typeof ApiOauthMarketplaceCallbackRoute
  '/api/oauth/$marketplace/start': typeof ApiOauthMarketplaceStartRoute
  '/api/suporte/anexos/$attachmentId': typeof ApiSuporteAnexosAttachmentIdRoute
  '/admin/chamados/': typeof AppAdminChamadosIndexRoute
  '/api/suporte/chamados/': typeof ApiSuporteChamadosIndexRoute
  '/api/admin/chamados/$ticketId/mensagens': typeof ApiAdminChamadosTicketIdMensagensRoute
  '/api/suporte/chamados/$ticketId/mensagens': typeof ApiSuporteChamadosTicketIdMensagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/lojas': typeof AppLojasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/cadastro': typeof AuthCadastroRoute
  '/login': typeof AuthLoginRoute
  '/fornecedores/$supplierId': typeof AppFornecedoresSupplierIdRoute
  '/publicacoes/nova': typeof AppPublicacoesNovaRoute
  '/suporte/$ticketId': typeof AppSuporteTicketIdRoute
  '/suporte/novo': typeof AppSuporteNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/financeiro/exportar': typeof ApiFinanceiroExportarRoute
  '/api/webhooks/$marketplace': typeof ApiWebhooksMarketplaceRoute
  '/oauth/mock/autorizar': typeof OauthMockAutorizarRoute
  '/fornecedores': typeof AppFornecedoresIndexRoute
  '/publicacoes': typeof AppPublicacoesIndexRoute
  '/suporte': typeof AppSuporteIndexRoute
  '/admin/chamados/$ticketId': typeof AppAdminChamadosTicketIdRoute
  '/api/oauth/$marketplace/callback': typeof ApiOauthMarketplaceCallbackRoute
  '/api/oauth/$marketplace/start': typeof ApiOauthMarketplaceStartRoute
  '/api/suporte/anexos/$attachmentId': typeof ApiSuporteAnexosAttachmentIdRoute
  '/admin/chamados': typeof AppAdminChamadosIndexRoute
  '/api/suporte/chamados': typeof ApiSuporteChamadosIndexRoute
  '/api/admin/chamados/$ticketId/mensagens': typeof ApiAdminChamadosTicketIdMensagensRoute
  '/api/suporte/chamados/$ticketId/mensagens': typeof ApiSuporteChamadosTicketIdMensagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/fornecedores': typeof AppFornecedoresRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/lojas': typeof AppLojasRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_auth/cadastro': typeof AuthCadastroRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/fornecedores/$supplierId': typeof AppFornecedoresSupplierIdRoute
  '/_app/publicacoes/nova': typeof AppPublicacoesNovaRoute
  '/_app/suporte/$ticketId': typeof AppSuporteTicketIdRoute
  '/_app/suporte/novo': typeof AppSuporteNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/financeiro/exportar': typeof ApiFinanceiroExportarRoute
  '/api/webhooks/$marketplace': typeof ApiWebhooksMarketplaceRoute
  '/oauth/mock/autorizar': typeof OauthMockAutorizarRoute
  '/_app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/_app/publicacoes/': typeof AppPublicacoesIndexRoute
  '/_app/suporte/': typeof AppSuporteIndexRoute
  '/_app/admin/chamados/$ticketId': typeof AppAdminChamadosTicketIdRoute
  '/api/oauth/$marketplace/callback': typeof ApiOauthMarketplaceCallbackRoute
  '/api/oauth/$marketplace/start': typeof ApiOauthMarketplaceStartRoute
  '/api/suporte/anexos/$attachmentId': typeof ApiSuporteAnexosAttachmentIdRoute
  '/_app/admin/chamados/': typeof AppAdminChamadosIndexRoute
  '/api/suporte/chamados/': typeof ApiSuporteChamadosIndexRoute
  '/api/admin/chamados/$ticketId/mensagens': typeof ApiAdminChamadosTicketIdMensagensRoute
  '/api/suporte/chamados/$ticketId/mensagens': typeof ApiSuporteChamadosTicketIdMensagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fornecedores'
    | '/dashboard'
    | '/financeiro'
    | '/lojas'
    | '/onboarding'
    | '/cadastro'
    | '/login'
    | '/fornecedores/$supplierId'
    | '/publicacoes/nova'
    | '/suporte/$ticketId'
    | '/suporte/novo'
    | '/api/auth/$'
    | '/api/financeiro/exportar'
    | '/api/webhooks/$marketplace'
    | '/oauth/mock/autorizar'
    | '/fornecedores/'
    | '/publicacoes/'
    | '/suporte/'
    | '/admin/chamados/$ticketId'
    | '/api/oauth/$marketplace/callback'
    | '/api/oauth/$marketplace/start'
    | '/api/suporte/anexos/$attachmentId'
    | '/admin/chamados/'
    | '/api/suporte/chamados/'
    | '/api/admin/chamados/$ticketId/mensagens'
    | '/api/suporte/chamados/$ticketId/mensagens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/financeiro'
    | '/lojas'
    | '/onboarding'
    | '/cadastro'
    | '/login'
    | '/fornecedores/$supplierId'
    | '/publicacoes/nova'
    | '/suporte/$ticketId'
    | '/suporte/novo'
    | '/api/auth/$'
    | '/api/financeiro/exportar'
    | '/api/webhooks/$marketplace'
    | '/oauth/mock/autorizar'
    | '/fornecedores'
    | '/publicacoes'
    | '/suporte'
    | '/admin/chamados/$ticketId'
    | '/api/oauth/$marketplace/callback'
    | '/api/oauth/$marketplace/start'
    | '/api/suporte/anexos/$attachmentId'
    | '/admin/chamados'
    | '/api/suporte/chamados'
    | '/api/admin/chamados/$ticketId/mensagens'
    | '/api/suporte/chamados/$ticketId/mensagens'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/admin'
    | '/_app/fornecedores'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/lojas'
    | '/_app/onboarding'
    | '/_auth/cadastro'
    | '/_auth/login'
    | '/_app/fornecedores/$supplierId'
    | '/_app/publicacoes/nova'
    | '/_app/suporte/$ticketId'
    | '/_app/suporte/novo'
    | '/api/auth/$'
    | '/api/financeiro/exportar'
    | '/api/webhooks/$marketplace'
    | '/oauth/mock/autorizar'
    | '/_app/fornecedores/'
    | '/_app/publicacoes/'
    | '/_app/suporte/'
    | '/_app/admin/chamados/$ticketId'
    | '/api/oauth/$marketplace/callback'
    | '/api/oauth/$marketplace/start'
    | '/api/suporte/anexos/$attachmentId'
    | '/_app/admin/chamados/'
    | '/api/suporte/chamados/'
    | '/api/admin/chamados/$ticketId/mensagens'
    | '/api/suporte/chamados/$ticketId/mensagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFinanceiroExportarRoute: typeof ApiFinanceiroExportarRoute
  ApiWebhooksMarketplaceRoute: typeof ApiWebhooksMarketplaceRoute
  OauthMockAutorizarRoute: typeof OauthMockAutorizarRoute
  ApiOauthMarketplaceCallbackRoute: typeof ApiOauthMarketplaceCallbackRoute
  ApiOauthMarketplaceStartRoute: typeof ApiOauthMarketplaceStartRoute
  ApiSuporteAnexosAttachmentIdRoute: typeof ApiSuporteAnexosAttachmentIdRoute
  ApiSuporteChamadosIndexRoute: typeof ApiSuporteChamadosIndexRoute
  ApiAdminChamadosTicketIdMensagensRoute: typeof ApiAdminChamadosTicketIdMensagensRoute
  ApiSuporteChamadosTicketIdMensagensRoute: typeof ApiSuporteChamadosTicketIdMensagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lojas': {
      id: '/_app/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AppLojasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/cadastro': {
      id: '/_auth/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/fornecedores/': {
      id: '/_app/fornecedores/'
      path: '/'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof AppFornecedoresIndexRouteImport
      parentRoute: typeof AppFornecedoresRouteRoute
    }
    '/_app/fornecedores/$supplierId': {
      id: '/_app/fornecedores/$supplierId'
      path: '/$supplierId'
      fullPath: '/fornecedores/$supplierId'
      preLoaderRoute: typeof AppFornecedoresSupplierIdRouteImport
      parentRoute: typeof AppFornecedoresRouteRoute
    }
    '/_app/publicacoes/': {
      id: '/_app/publicacoes/'
      path: '/publicacoes'
      fullPath: '/publicacoes/'
      preLoaderRoute: typeof AppPublicacoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/publicacoes/nova': {
      id: '/_app/publicacoes/nova'
      path: '/publicacoes/nova'
      fullPath: '/publicacoes/nova'
      preLoaderRoute: typeof AppPublicacoesNovaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suporte/': {
      id: '/_app/suporte/'
      path: '/suporte'
      fullPath: '/suporte/'
      preLoaderRoute: typeof AppSuporteIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suporte/$ticketId': {
      id: '/_app/suporte/$ticketId'
      path: '/suporte/$ticketId'
      fullPath: '/suporte/$ticketId'
      preLoaderRoute: typeof AppSuporteTicketIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suporte/novo': {
      id: '/_app/suporte/novo'
      path: '/suporte/novo'
      fullPath: '/suporte/novo'
      preLoaderRoute: typeof AppSuporteNovoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/financeiro/exportar': {
      id: '/api/financeiro/exportar'
      path: '/api/financeiro/exportar'
      fullPath: '/api/financeiro/exportar'
      preLoaderRoute: typeof ApiFinanceiroExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/$marketplace': {
      id: '/api/webhooks/$marketplace'
      path: '/api/webhooks/$marketplace'
      fullPath: '/api/webhooks/$marketplace'
      preLoaderRoute: typeof ApiWebhooksMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/mock/autorizar': {
      id: '/oauth/mock/autorizar'
      path: '/oauth/mock/autorizar'
      fullPath: '/oauth/mock/autorizar'
      preLoaderRoute: typeof OauthMockAutorizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/chamados/': {
      id: '/_app/admin/chamados/'
      path: '/chamados'
      fullPath: '/admin/chamados/'
      preLoaderRoute: typeof AppAdminChamadosIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/chamados/$ticketId': {
      id: '/_app/admin/chamados/$ticketId'
      path: '/chamados/$ticketId'
      fullPath: '/admin/chamados/$ticketId'
      preLoaderRoute: typeof AppAdminChamadosTicketIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/oauth/$marketplace/callback': {
      id: '/api/oauth/$marketplace/callback'
      path: '/api/oauth/$marketplace/callback'
      fullPath: '/api/oauth/$marketplace/callback'
      preLoaderRoute: typeof ApiOauthMarketplaceCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/$marketplace/start': {
      id: '/api/oauth/$marketplace/start'
      path: '/api/oauth/$marketplace/start'
      fullPath: '/api/oauth/$marketplace/start'
      preLoaderRoute: typeof ApiOauthMarketplaceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suporte/anexos/$attachmentId': {
      id: '/api/suporte/anexos/$attachmentId'
      path: '/api/suporte/anexos/$attachmentId'
      fullPath: '/api/suporte/anexos/$attachmentId'
      preLoaderRoute: typeof ApiSuporteAnexosAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suporte/chamados/': {
      id: '/api/suporte/chamados/'
      path: '/api/suporte/chamados'
      fullPath: '/api/suporte/chamados/'
      preLoaderRoute: typeof ApiSuporteChamadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/chamados/$ticketId/mensagens': {
      id: '/api/admin/chamados/$ticketId/mensagens'
      path: '/api/admin/chamados/$ticketId/mensagens'
      fullPath: '/api/admin/chamados/$ticketId/mensagens'
      preLoaderRoute: typeof ApiAdminChamadosTicketIdMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suporte/chamados/$ticketId/mensagens': {
      id: '/api/suporte/chamados/$ticketId/mensagens'
      path: '/api/suporte/chamados/$ticketId/mensagens'
      fullPath: '/api/suporte/chamados/$ticketId/mensagens'
      preLoaderRoute: typeof ApiSuporteChamadosTicketIdMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminChamadosTicketIdRoute: typeof AppAdminChamadosTicketIdRoute
  AppAdminChamadosIndexRoute: typeof AppAdminChamadosIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminChamadosTicketIdRoute: AppAdminChamadosTicketIdRoute,
  AppAdminChamadosIndexRoute: AppAdminChamadosIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppFornecedoresRouteRouteChildren {
  AppFornecedoresSupplierIdRoute: typeof AppFornecedoresSupplierIdRoute
  AppFornecedoresIndexRoute: typeof AppFornecedoresIndexRoute
}

const AppFornecedoresRouteRouteChildren: AppFornecedoresRouteRouteChildren = {
  AppFornecedoresSupplierIdRoute: AppFornecedoresSupplierIdRoute,
  AppFornecedoresIndexRoute: AppFornecedoresIndexRoute,
}

const AppFornecedoresRouteRouteWithChildren =
  AppFornecedoresRouteRoute._addFileChildren(AppFornecedoresRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppFornecedoresRouteRoute: typeof AppFornecedoresRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppLojasRoute: typeof AppLojasRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPublicacoesNovaRoute: typeof AppPublicacoesNovaRoute
  AppSuporteTicketIdRoute: typeof AppSuporteTicketIdRoute
  AppSuporteNovoRoute: typeof AppSuporteNovoRoute
  AppPublicacoesIndexRoute: typeof AppPublicacoesIndexRoute
  AppSuporteIndexRoute: typeof AppSuporteIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppFornecedoresRouteRoute: AppFornecedoresRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppLojasRoute: AppLojasRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPublicacoesNovaRoute: AppPublicacoesNovaRoute,
  AppSuporteTicketIdRoute: AppSuporteTicketIdRoute,
  AppSuporteNovoRoute: AppSuporteNovoRoute,
  AppPublicacoesIndexRoute: AppPublicacoesIndexRoute,
  AppSuporteIndexRoute: AppSuporteIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCadastroRoute: AuthCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFinanceiroExportarRoute: ApiFinanceiroExportarRoute,
  ApiWebhooksMarketplaceRoute: ApiWebhooksMarketplaceRoute,
  OauthMockAutorizarRoute: OauthMockAutorizarRoute,
  ApiOauthMarketplaceCallbackRoute: ApiOauthMarketplaceCallbackRoute,
  ApiOauthMarketplaceStartRoute: ApiOauthMarketplaceStartRoute,
  ApiSuporteAnexosAttachmentIdRoute: ApiSuporteAnexosAttachmentIdRoute,
  ApiSuporteChamadosIndexRoute: ApiSuporteChamadosIndexRoute,
  ApiAdminChamadosTicketIdMensagensRoute:
    ApiAdminChamadosTicketIdMensagensRoute,
  ApiSuporteChamadosTicketIdMensagensRoute:
    ApiSuporteChamadosTicketIdMensagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
